version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongodb:27017/gestao_relatorios
      PORT: 3001
      JWT_SECRET: seu_segredo_jwt_muito_forte_aqui
      EMAIL_USER: seu_email@example.com
      EMAIL_PASS: sua_senha_email_app
    depends_on:
      - mongodb
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:3001
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge